version: '3'

services:
# Jenkins - On a container with docker installer (does't work on docker for windows)
  jenkins:
    build: ./jenkins-image
    container_name: "jenkins"
    ports:
    - "8080:8080"
    volumes:
    - jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd-network

# SonarQube - without DB
#sonarqube:
#  image: sonarqube:lts
#  container_name: "sonarqube"
#  ports:
#    - "9000:9000"
#  networks:
#    - cicd-network

# SonarQube - with DB
  sonarqube:
    image: sonarqube:lts
    container_name: "sonarqube"
    ports:
      - "9000:9000"
    networks:
      - cicd-network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

# SonarQube - Postgres DB
  sonarqube-db:
    image: postgres
    container_name: "sonarqube-db"
    networks:
      - cicd-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

# Nexus 3 Repository
  nexus3:
    image: sonatype/nexus3:3.14.0
    container_name: "nexus3"
    ports:
    - "8081:8081"
    volumes:
    - nexus-data:/nexus-data
    networks:
      - cicd-network

networks:
  cicd-network:

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
  nexus-data: