version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: "jenkins"
    ports:
    - "8080:8080"
    volumes:
    - jenkins_home:/var/jenkins_home
    networks:
      - cicd-network

  sonarqube:
    image: sonarqube:lts
    container_name: "sonarqube"
    ports:
      - "9000:9000"
    networks:
      - cicd-network
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonarqube-db:
    image: postgres
    container_name: "sonarqube-db"
    networks:
      - cicd-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  cicd-network:

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: